# Generated by Django 3.0.5 on 2020-05-18 20:05

from django.db import migrations


def forwards_func(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')
    Product = apps.get_model('mainapp', 'Product')
    Category.objects.bulk_create([
        Category(
            slug='sport_equip',
            name='Спортивный инвентарь',
            description='Снаряды, приспособления и принадлежности для занятий спортом и физических упражнений'
        ),
        Category(
            slug='personal_def',
            name='Средства индивидуальной защиты',
            description='Предметы индивидуального использования, предназначенные для защиты органов дыхания, зрения, слуха, а так же конечностей'
        ),
        Category(
            slug='creativity_goods',
            name='Товары для творчества',
            description='Предметы, прямо или косвенно предназначенные для создания произведений искусства'
        ),
        Category(
            slug='stationery',
            name='Канцелярские товары',
            description='Принадлежности для письма и ведения документооборота'
        ),
    ])
    Product.objects.bulk_create([
        Product(
            slug='kettlebell',
            image='product_img/kettlebell.jpg',
            name='Гири тов.Корейко',
            category=Category.objects.get(slug='sport_equip'),
            description='Гири чугунные полуторапудовые.',
            price=7.40
        ),
        Product(
            slug='gasmask',
            image='product_img/gasmask.jpg',
            name='Противогаз гражданский',
            category=Category.objects.get(slug='personal_def'),
            description='Противогаз для применения во время учений по гражданской обороне.',
            price=3.62
        ),
        Product(
            slug='solemnset',
            image='product_img/solemnset.jpg',
            name='Торжественный комплект',
            category=Category.objects.get(slug='creativity_goods'),
            description='Незаменимое пособие для сочинения юбилейных статей, табельных фельетонов, а также парадных стихотворений, од и тропарей',
            price=25.00
        ),
        Product(
            slug='turkish_typewriter',
            image='product_img/typewriter.jpg',
            name='Машинка с турецким акцентом',
            category=Category.objects.get(slug='stationery'),
            description='Старая пишущая машинка &quot;Адлер&quot;, в которой не хватает буквы &quot;е&quot;, и ее приходится заменять буквой &quot;э&quot;.',
            price=35.50
        ),
    ])


def reverse_func(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')
    Product = apps.get_model('mainapp', 'Product')
    Product.objects.all().delete()
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
