# Generated by Django 3.0.5 on 2020-05-25 01:40

from random import sample, randint
from django.db import migrations

LOREM = """
Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur Excepteur sint occaecat cupidatat
non proident sunt in culpa qui officia deserunt mollit anim id est laborum
"""


def forwards_func(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')
    Product = apps.get_model('mainapp', 'Product')
    for cat in Category.objects.all():
        Product.objects.bulk_create([
            Product(
                slug='_'.join(sample(LOREM.split(), 3)),
                name=' '.join(sample(LOREM.split(), 3)).capitalize(),
                category=cat,
                description=' '.join(sample(LOREM.split(), 30)).capitalize(),
                price=randint(120, 25000) / 100
            )
            for _ in range(5)
        ])


def reverse_func(apps, schema_editor):
    Category = apps.get_model('mainapp', 'Category')
    Product = apps.get_model('mainapp', 'Product')
    Product.objects.all().delete()
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200525_0435'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
