# Generated by Django 3.0.5 on 2020-05-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_fill_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('state', models.CharField(choices=[('active', 'активная корзина'), ('chkout', 'оформлен заказ'), ('archiv', 'история заказов'), ('delete', 'корзина удалена')], default='active', max_length=6, verbose_name='статус')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='покупатель')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
                'ordering': ('-started',),
            },
        ),
        migrations.CreateModel(
            name='BasketSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='basketapp.UserBasket', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='mainapp.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар корзины',
                'verbose_name_plural': 'товары корзины',
                'ordering': ('basket',),
            },
        ),
    ]
