# Generated by Django 2.2.13 on 2020-06-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_fill_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(max_length=40, verbose_name='код подтверждения')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
