# Generated by Django 2.2.13 on 2020-06-11 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('payment', models.CharField(blank=True, choices=[('cash', 'Оплата наличными'), ('card', 'Оплата банковской картой'), ('chck', 'Безналичная оплата')], max_length=4, verbose_name='предпочтительный метод оплаты')),
                ('address', models.TextField(blank=True, verbose_name='адрес доставки')),
            ],
        ),
    ]
